<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Survey</title>
</head>
<body>
	<!-- Navigation -->
    <nav class="main-menu">
        <a id="logo" href="index.php">
        	<h1>Michelin Guides</h1>
        </a>
        <ul>
            <li><a href="#first">Introduction</a></li>
            <li><a href="#second">History</a></li>
            <li><a href="#third">Assessment Criteria and Core Values</a></li>
            <li><a href="#forth">Three-Star Michelin Restaurants</a></li>
            <li><a href="survey.html">Survey</a><li>
        </ul>
    </nav>